# Site settings
title: Architektai Vilniuje | arkilida.lt
description: > # this means to ignore newlines until "baseurl:"
  UAB Arkilida, architektai Vilniuje. Kuriame prakti≈°kus namus, kuriuose patogu ir malonu gyventi.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arkilida.lt" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
destination: docs
exclude: ['TODO', 'Gemfile']
